version: "2"

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-conf
    entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node